version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-chatter}
      POSTGRES_DB: ${POSTGRES_DB:-chatapp}
  back :
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-pg.tchatche.rs}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-chatapp}
      POSTGRES_USER: ${POSTGRES_USER:-chatter}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    links:
      - postgres:${POSTGRES_HOST:-pg.tchatche.rs}
    depends_on:
      - postgres
    build: 
      context: ./ 
      dockerfile: Dockerfile_back
    volumes:
      - static:/home/usr/back/static
      - ./env:/home/usr/back/.env:ro
  front :
    volumes:
      - ${SSL_CERTIFICATE_PATH}:/usr/nginx/home/certs/cert.crt:ro
      - ${SSL_CERTIFICATE_KEY}:/usr/nginx/home/certs/key.pem:ro
      - ${SSL_DHPARAM_PATH}:/usr/nginx/home/certs/ssl-dhparams.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back
    links:
      - back:back.tchatche.rs
    build: 
      context: ./ 
      dockerfile: Dockerfile_front
    ports:
      - "80:80"
      - "443:443"
  cli :
    links:
      - postgres:${POSTGRES_HOST:-pg.tchatche.rs}
    depends_on:
      - postgres
    build: 
      context: ./ 
      dockerfile: Dockerfile_tct
volumes:
  db:
  static:
