version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-chatter}
      POSTGRES_DB: ${POSTGRES_DB:-chatapp}
  back :
    user: "${UID:-1000}:${GID:-1000}"
    links:
      - postgres:${POSTGRES_HOST:-pg.tchatche.rs}
    depends_on:
      - postgres
    build: 
      context: ./ 
      dockerfile: Dockerfile_back
    volumes:
      - static:/home/usr/back/static
  front :
    volumes:
      - /etc/letsencrypt:/usr/nginx/home/certs:ro
    depends_on:
      - back
    links:
      - back:back.tchatche.rs
    build: 
      context: ./ 
      dockerfile: Dockerfile_front
    ports:
      - "80:80"
      - "443:443"
  cli :
    links:
      - postgres:${POSTGRES_HOST:-pg.tchatche.rs}
    depends_on:
      - postgres
    build: 
      context: ./ 
      dockerfile: Dockerfile_tct
volumes:
  db:
  static:
