version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-chatter}
      POSTGRES_DB: ${POSTGRES_DB:-chatapp}
    ports:
      - "5432:5432"
  cli :
    links:
      - postgres:${POSTGRES_HOST:-pg.tchatche.rs}
    depends_on:
      - postgres
    build: 
      context: ./ 
      dockerfile: Dockerfile_tct
volumes:
  db:

