version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  back :
    links:
      - postgres:pg.tchatche.rs
      - redis:redis.tchatche.rs
    depends_on:
      - postgres
      - redis
    build: 
      context: ./ 
      dockerfile: Dockerfile_back
    volumes:
      - static:/home/usr/back/static
  front :
    volumes:
      - /etc/letsencrypt:/usr/nginx/home/certs:ro
    depends_on:
      - back
    links:
      - back:back.tchatche.rs
    build: 
      context: ./ 
      dockerfile: Dockerfile_front
    ports:
      - "80:80"
      - "443:443"
volumes:
  db:
  redis:
  static:
