version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  redis:
    image: redis:7.0.2
    restart: always
    volumes: 
      - redis:/data
  back :
    links:
      - postgres:pg.tchatche.rs
      - redis:redis.tchatche.rs
    depends_on:
      - postgres
      - redis
    build: 
      context: ./ 
      dockerfile: Dockerfile_back
  migrations :
    depends_on:
      - postgres
    links:
      - postgres:pg.tchatche.rs
    build: 
      context: ./ 
      dockerfile: Dockerfile_migrations
  front :
    depends_on:
      - back
    links:
      - back:back.tchatche.rs
    build: 
      context: ./ 
      dockerfile: Dockerfile_front
    ports:
      - "80:80"
volumes:
  db:
  redis:
