[package]
name = "tchatchers_back"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.15" , features = ["ws", "headers"] }
headers = "0.3"
magic-crypt = "3.1.10"
tokio = { version = "1.0", features = ["full"] }
tchatchers_core = { path = "../tchatchers_core", features = ["back"] }
sqlx-core = { version = "0.6.1", features = ["postgres"] }
dotenv = "0.15.0"
futures-util = "0.3.24"
tower-cookies = "0.7.0"
regex = "1.6.0"
lazy_static = "1.4.0"
serde_json = "1.0.85"
chrono = { version = "0.4.22", features = ["serde"] }
r2d2 = "0.8.10"
redis = "0.21.6"
