[package]
name = "tchatchers_back"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.4", features = ["ws", "headers", "multipart"] }
tokio = { version = "1.0", features = ["full"] }
tchatchers_core = { path = "../tchatchers_core", features = ["back"] }
sqlx-core = { version = "0.6.1", features = ["postgres"] }
dotenv = "0.15.0"
futures-util = "0.3.24"
serde_json = "1.0.85"
uuid = { version = "1.1.2", features = ["v4", "serde", "js"] }
tower-http = { version = "0.3.5", features = ["sensitive-headers", "request-id", "fs", "trace", "util"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum-extra = { version = "0.4.0", features = ["cookie"] }
tracing = "0.1.37"
validator = { version = "0.16.0"}
serde = "1.0.151"
sqlx = "0.6.2"
tower = "0.4.13"
