[package]
name = "tchatchers_core"
version = "0.1.0"
edition = "2021"

[features]
back = ["dep:sqlx", "dep:rust-argon2", "dep:axum"]
front = []


[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
derivative = "2.2.0"
jsonwebtoken = "8.1.1"
rand = "0.8.5"
rust-argon2 = { version = "1.0.0", optional = true}
serde = { version = "1.0.144", features = ["derive"] }
sqlx = { version = "0.6", features = ["runtime-async-std-native-tls", "postgres", "uuid", "chrono"], optional = true }
uuid = { version = "1.1.2", features = ["v4", "serde", "js"] }
validator = { version = "0.16.0", features = ["derive"] }
axum = { version = "0.6.1", optional = true }
regex = "1.7.0"
lazy_static = "1.4.0"
derive_more = "0.99.17"
log = "0.4.17"
