[package]
name = "tchatchers_front"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
futures = "0.3.23"
gloo-console = "0.2.3"
gloo-net = "0.2.4"
gloo-timers = "0.2.4"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"
web-sys = { version = "0.3.60", features = ["HtmlDocument", "FileReader"] }
yew = "0.19.3"
yew-agent = "0.1.0"
yew-router = "0.16.0"
tchatchers_core = { path = "../tchatchers_core"}
linked_hash_set = "0.1.4"
chrono = { version = "0.4.22", features = ["serde"] }
base64 = "0.13.0"
js-sys = "0.3.60"
reqwest-wasm = "0.11.0"
