[package]
name = "tchatchers_core"
version = "0.1.0"
edition = "2021"


[features]
back = ["dep:sqlx", "dep:redis", "dep:r2d2"]


[dependencies]
chrono = "0.4.22"
derivative = "2.2.0"
jsonwebtoken = "8.1.1"
r2d2 = { version = "0.8.10", optional = true}
redis = { version =  "0.21.6" , optional = true, features = ["r2d2"]}
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
sqlx = { version = "0.6", features = [ "runtime-async-std-native-tls" , "postgres"], optional = true }
uuid = { version = "1.1.2", features = ["v4", "serde", "js"] }
